
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../integrations/supabase/types';

const SUPABASE_URL = "https://gcejhxrwyftlzbztngug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjZWpoeHJ3eWZ0bHpienRuZ3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MDM3NTksImV4cCI6MjA1NDk3OTc1OX0.dTPrJembkfcqPWyByD08JrCotwee_cgLTzo18k2buLg";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
